#!/bin/bash
# make it executable
#need to install task_spooler : sudo apt-get install task-spooler
# first argument must be a command
# ARGS="${@: 2}"
# ARGS="$@" try also to put args in array, use $# for numbers ${ARGS[0]}...
ARGS="${@: 2}"
COMMAND=$1
./log "******************"
./log $0 "Enqueue : $COMMAND $ARGS"
./log $0 "Queue job id : $(tsp $COMMAND \"$ARGS\")"
./log "******************"
