#!/home/numeric/.rbenv/shims/ruby
# 2 parameters needed : filedirectory and filename
require 'csv'
require 'json'
require 'time'

if ARGV[0] && ARGV[1]
  filename = ARGV[0]
  filepath = "#{ARGV[0]}/#{ARGV[1]}"
  `../log $0 "START parsing #{filepath}"`
  /(?<logdate>\d{4}.\d{2}.\d{2})/ =~ filename
  options = { col_sep: ';', quote_char: "\"", headers: :first_row }
  my_csv = CSV.read(filepath, options)
  headers = my_csv.headers - ['Heure']
  headers.compact!
  logs = []
  my_csv.each do |row|
    unix_timestamps = Time.parse(logdate + '-' + my_csv[1]['Heure']).to_i
    log = { ts: unix_timestamps * 1000 } # api needs milliseconds precision
    values = {}
    headers.each do |header|
      values[header] = row[header]
    end
    log['values'] = values
    logs << log
  end
  json_log = JSON.generate(logs)
  if json_log
    puts json_log
  else
    puts 'ERROR'
  end
else
  `../log $0 "ERROR parameters problem"
end
